import { Router } from 'express';
import { authenticate, requireRole } from '../middlewares/auth.middleware';
import { createScheduleBlock, deleteScheduleBlock, listScheduleBlocks, updateScheduleBlock } from '../controllers/scheduleBlock.controller';
const router = Router();
router.use(authenticate);
router.get('/', listScheduleBlocks);
router.post('/', requireRole(['DOCTOR', 'CLINIC_ADMIN', 'ASSISTANT']), createScheduleBlock);
router.patch('/:id', requireRole(['DOCTOR']), updateScheduleBlock);
router.delete('/:id', requireRole(['DOCTOR']), deleteScheduleBlock);
export default router;
